language: java

jdk:
- oraclejdk8

env:
  - NODE_VERSION="8"

before_install:
  - nvm install $NODE_VERSION
  - node --version
  - npm --version

install:
  - npm install -g serverless

after_script:
  - ./deploy.sh
