service: generate-picker-data-file

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: build/distributions/generate-picker-data-file.zip

functions:
  generate:
    handler: com.serverless.Handler
    events:
      - http:
          path: generate
          method: post
